spring.application.name=backend
spring.docker.compose.enabled=false

# AWSでの設定。
# spring-profile-active=awsを設定。
spring.config.activate.on-profile=aws

# 値はパラメータストアとシークレットマネージャーから取得するようになっています。
# 環境変数 ENV で設定する。

# IAM認証を使用するため、SecretsManagerを使う予定はないが、一応使用しておく。
# parameter storeの場合は、 パラメータストアのキーのprefix
# secrets managerの場合は、secrets managerの名前。JSONのキーを指定する。
# 両方に同じ値がある場合、後ろにあるほうで上書き。
spring.config.import=aws-parameterstore:/sandbox00/backend/${ENV}/,aws-secretsmanager:/sandbox00/backend/${ENV}/

# driver classはawsのものを使うため、この設定はfalseでよい。
# IAM認証は行うが、それを行うのはHikari CPではないため。
# spring.datasource.driver-class-name=software.amazon.jdbc.Driver
spring.datasource.hikari.data-source-properties.awsIam=false

# driver classは固定でもいいか。
spring.datasource.driver-class-name=software.amazon.jdbc.Driver
spring.datasource.url=${db/url}
spring.datasource.username=${db/username}
spring.datasource.password=${db/password}

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax
