# このプロパティファイルは使用しません。
# ローカル環境では application-local.properties 
# AWS環境では application-aws.properties 
# を使用します。
 
# 理由。
# ひとつのプロパティファイルですべての設定を見ることができ、シンプルになるため。
# application.properties と application-<環境>.properties の2つを見て、実際にどの値が使用されるかを見るのは困難。

#spring.profiles.active=${spring.profiles.active:#{T(java.lang.Objects).requireNonNull(null, 'SPRING_PROFILES_ACTIVE is not set!')}}
